// Signal Outcomes Database Helper
// Manages persistence and retrieval of trading signals for ML training

import { createSupabaseBrowserClient } from '../api/supabase-client';
import { TradingSignal, Direction } from '../analysis/signal-generator';

// ─── Types ────────────────────────────────────────────────────────────────────

export interface SignalOutcome {
  signal_id: string;
  event_id: string;
  market_id: string;
  platform: 'polymarket' | 'kalshi';
  predicted_direction: Direction;
  predicted_prob: number;
  confidence: number;
  edge: number;
  signal_type: string;
  urgency: string;
  features: Record<string, unknown>;
  created_at: string;
  resolution_date?: string;
  outcome?: 'YES' | 'NO';
  was_correct?: boolean;
  pnl?: number;
}

export interface PerformanceMetrics {
  total_signals: number;
  resolved_signals: number;
  unresolved_signals: number;
  win_rate: number;
  avg_confidence: number;
  avg_edge: number;
  brier_score: number;
  total_pnl: number;
  avg_pnl: number;
  by_signal_type: Record<string, {
    count: number;
    win_rate: number;
    avg_pnl: number;
  }>;
  by_platform: Record<string, {
    count: number;
    win_rate: number;
    avg_pnl: number;
  }>;
}

// ─── Database Operations ──────────────────────────────────────────────────────

/**
 * Log a trading signal to the database for ML training.
 * Extracts features from the signal and stores them for future model training.
 * 
 * @param signal The trading signal generated by signal-generator
 * @param features Additional features to store (optional, will merge with extracted features)
 * @returns The created signal_id, or null if insert failed
 */
export async function logSignal(
  signal: TradingSignal,
  additionalFeatures?: Record<string, unknown>
): Promise<string | null> {
  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || process.env.SUPABASE_URL;
  const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || process.env.SUPABASE_ANON_KEY;

  if (!supabaseUrl || !supabaseKey) {
    console.error('[logSignal] Missing Supabase credentials');
    return null;
  }

  const client = createSupabaseBrowserClient(supabaseUrl, supabaseKey);

  // Only log if we have a suggested action (HOLD signals are less interesting for training)
  if (!signal.suggested_action) {
    return null;
  }

  const topMatch = signal.matches[0];
  if (!topMatch) {
    return null;
  }

  const topMarket = topMatch.market;

  // Extract all relevant features for ML training
  const features = {
    // Sentiment features
    sentiment: signal.sentiment?.sentiment,
    sentiment_confidence: signal.sentiment?.confidence,
    
    // Market features
    yes_price: topMarket.yesPrice,
    no_price: topMarket.noPrice,
    volume_24h: topMarket.volume24h,
    category: topMarket.category,
    one_day_price_change: topMarket.oneDayPriceChange,
    is_anomalous: topMarket.is_anomalous,
    
    // Match features
    match_confidence: topMatch.confidence,
    matched_keywords: topMatch.matchedKeywords,
    num_matches: signal.matches.length,
    
    // Signal metadata
    valid_until_seconds: signal.valid_until_seconds,
    is_near_resolution: signal.is_near_resolution,
    processing_time_ms: signal.metadata.processing_time_ms,
    tweet_text: signal.metadata.tweet_text,
    
    // Arbitrage features (if present)
    has_arbitrage: !!signal.arbitrage,
    arbitrage_spread: signal.arbitrage?.spread,
    arbitrage_net_spread: signal.arbitrage?.net_spread,
    arbitrage_profit_potential: signal.arbitrage?.profitPotential,
    
    // Position sizing
    kelly_fraction: signal.suggested_action.position_size.fraction,
    kelly_full: signal.suggested_action.position_size.kelly_full,
    risk_level: signal.suggested_action.position_size.risk_level,
    vol_regime: signal.suggested_action.position_size.vol_regime,

    ...(signal.ml_score_shadow
      ? {
          ml_score_shadow_probability: signal.ml_score_shadow.probability,
          ml_score_shadow_confidence: signal.ml_score_shadow.confidence,
          ml_score_shadow_source: signal.ml_score_shadow.source,
          ml_score_shadow_model_version: signal.ml_score_shadow.model_version,
        }
      : {}),

    // Merge additional features
    ...additionalFeatures,
  };

  const { data, error } = await client
    .from('signal_outcomes')
    .insert({
      event_id: signal.event_id,
      market_id: topMarket.id,
      platform: topMarket.platform,
      predicted_direction: signal.suggested_action.direction,
      predicted_prob: calculateImpliedProbability(
        signal.sentiment?.sentiment || 'neutral',
        signal.sentiment?.confidence || 0
      ),
      confidence: signal.suggested_action.confidence,
      edge: signal.suggested_action.edge,
      signal_type: signal.signal_type,
      urgency: signal.urgency,
      features,
    } as any)
    .select('signal_id')
    .single();

  if (error) {
    console.error('[logSignal] Failed to insert signal:', error);
    return null;
  }

  return (data as any)?.signal_id || null;
}

/**
 * Update a signal with its resolution outcome.
 * 
 * @param signalId The UUID of the signal to update
 * @param outcome The actual market resolution ('YES' or 'NO')
 * @param wasCorrect Whether the prediction was correct
 * @param pnl Profit/loss if trade was executed (optional)
 */
export async function updateResolution(
  signalId: string,
  outcome: 'YES' | 'NO',
  wasCorrect: boolean,
  pnl?: number
): Promise<boolean> {
  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || process.env.SUPABASE_URL;
  const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || process.env.SUPABASE_ANON_KEY;

  if (!supabaseUrl || !supabaseKey) {
    console.error('[updateResolution] Missing Supabase credentials');
    return false;
  }

  const client = createSupabaseBrowserClient(supabaseUrl, supabaseKey);

  const { error } = await (client
    .from('signal_outcomes') as any)
    .update({
      resolution_date: new Date().toISOString(),
      outcome,
      was_correct: wasCorrect,
      pnl: pnl ?? null,
    })
    .eq('signal_id', signalId);

  if (error) {
    console.error('[updateResolution] Failed to update signal:', error);
    return false;
  }

  return true;
}

/**
 * Get all signals that have not yet been resolved.
 * Useful for building a resolution monitoring system.
 * 
 * @returns Array of unresolved signals, ordered by creation date (oldest first)
 */
export async function getUnresolvedSignals(): Promise<SignalOutcome[]> {
  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || process.env.SUPABASE_URL;
  const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || process.env.SUPABASE_ANON_KEY;

  if (!supabaseUrl || !supabaseKey) {
    console.error('[getUnresolvedSignals] Missing Supabase credentials');
    return [];
  }

  const client = createSupabaseBrowserClient(supabaseUrl, supabaseKey);

  const { data, error } = await client
    .from('signal_outcomes')
    .select('*')
    .is('resolution_date', null)
    .order('created_at', { ascending: true });

  if (error) {
    console.error('[getUnresolvedSignals] Query failed:', error);
    return [];
  }

  return (data as SignalOutcome[]) || [];
}

/**
 * Get recent performance metrics for the signal generator.
 * Calculates win rate, Brier score, and PnL over the specified time window.
 * 
 * @param days Number of days to look back (default: 30)
 * @returns Aggregated performance metrics
 */
export async function getRecentPerformance(days: number = 30): Promise<PerformanceMetrics | null> {
  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || process.env.SUPABASE_URL;
  const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || process.env.SUPABASE_ANON_KEY;

  if (!supabaseUrl || !supabaseKey) {
    console.error('[getRecentPerformance] Missing Supabase credentials');
    return null;
  }

  const client = createSupabaseBrowserClient(supabaseUrl, supabaseKey);

  const cutoffDate = new Date();
  cutoffDate.setDate(cutoffDate.getDate() - days);

  const { data, error } = await client
    .from('signal_outcomes')
    .select('*')
    .gte('created_at', cutoffDate.toISOString());

  if (error) {
    console.error('[getRecentPerformance] Query failed:', error);
    return null;
  }

  const signals = (data as SignalOutcome[]) || [];

  if (signals.length === 0) {
    return {
      total_signals: 0,
      resolved_signals: 0,
      unresolved_signals: 0,
      win_rate: 0,
      avg_confidence: 0,
      avg_edge: 0,
      brier_score: 0,
      total_pnl: 0,
      avg_pnl: 0,
      by_signal_type: {},
      by_platform: {},
    };
  }

  const resolved = signals.filter(s => s.resolution_date !== null);
  const unresolved = signals.filter(s => s.resolution_date === null);

  // Win rate
  const correct = resolved.filter(s => s.was_correct === true).length;
  const win_rate = resolved.length > 0 ? correct / resolved.length : 0;

  // Average confidence and edge
  const avg_confidence = signals.reduce((sum, s) => sum + s.confidence, 0) / signals.length;
  const avg_edge = signals.reduce((sum, s) => sum + s.edge, 0) / signals.length;

  // Brier score (lower is better, 0 = perfect)
  const brier_score = resolved.length > 0
    ? resolved.reduce((sum, s) => {
        const predicted = s.predicted_prob;
        const actual = s.outcome === 'YES' ? 1 : 0;
        return sum + Math.pow(predicted - actual, 2);
      }, 0) / resolved.length
    : 0;

  // PnL
  const pnlSignals = resolved.filter(s => s.pnl !== null && s.pnl !== undefined);
  const total_pnl = pnlSignals.reduce((sum, s) => sum + (s.pnl || 0), 0);
  const avg_pnl = pnlSignals.length > 0 ? total_pnl / pnlSignals.length : 0;

  // Breakdowns by signal_type
  const by_signal_type: Record<string, { count: number; win_rate: number; avg_pnl: number }> = {};
  for (const signal of resolved) {
    if (!by_signal_type[signal.signal_type]) {
      by_signal_type[signal.signal_type] = { count: 0, win_rate: 0, avg_pnl: 0 };
    }
    by_signal_type[signal.signal_type].count++;
  }

  for (const type in by_signal_type) {
    const typeSignals = resolved.filter(s => s.signal_type === type);
    const typeCorrect = typeSignals.filter(s => s.was_correct).length;
    const typePnl = typeSignals.filter(s => s.pnl !== null).reduce((sum, s) => sum + (s.pnl || 0), 0);
    by_signal_type[type].win_rate = typeSignals.length > 0 ? typeCorrect / typeSignals.length : 0;
    by_signal_type[type].avg_pnl = typeSignals.length > 0 ? typePnl / typeSignals.length : 0;
  }

  // Breakdowns by platform
  const by_platform: Record<string, { count: number; win_rate: number; avg_pnl: number }> = {};
  for (const signal of resolved) {
    if (!by_platform[signal.platform]) {
      by_platform[signal.platform] = { count: 0, win_rate: 0, avg_pnl: 0 };
    }
    by_platform[signal.platform].count++;
  }

  for (const platform in by_platform) {
    const platformSignals = resolved.filter(s => s.platform === platform);
    const platformCorrect = platformSignals.filter(s => s.was_correct).length;
    const platformPnl = platformSignals.filter(s => s.pnl !== null).reduce((sum, s) => sum + (s.pnl || 0), 0);
    by_platform[platform].win_rate = platformSignals.length > 0 ? platformCorrect / platformSignals.length : 0;
    by_platform[platform].avg_pnl = platformSignals.length > 0 ? platformPnl / platformSignals.length : 0;
  }

  return {
    total_signals: signals.length,
    resolved_signals: resolved.length,
    unresolved_signals: unresolved.length,
    win_rate,
    avg_confidence,
    avg_edge,
    brier_score,
    total_pnl,
    avg_pnl,
    by_signal_type,
    by_platform,
  };
}

// ─── Helper Functions ─────────────────────────────────────────────────────────

function calculateImpliedProbability(sentiment: string, confidence: number): number {
  if (sentiment === 'neutral') return 0.5;
  if (sentiment === 'bullish') {
    return 0.5 + confidence * 0.4; // 0.5 → 0.9
  }
  return 0.5 - confidence * 0.4;   // 0.1 → 0.5
}
