/**
 * Embedding-based market matcher (Google Gemini).
 *
 * Mirrors the KeywordMatcher.match(text) interface so the eval harness can
 * swap between them. Loads precomputed market embeddings from disk; embeds
 * each query tweet on demand and ranks markets by cosine similarity.
 *
 * Cache file generated by scripts/embed-markets.ts.
 *
 * NOT wired into production yet — used only by the eval harness for
 * side-by-side comparison vs the keyword matcher.
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';
import { createHash } from 'node:crypto';
import { GoogleGenerativeAI } from '@google/generative-ai';
import type { Market, MarketMatch } from '../types/market';
import { isPromotionalContent } from './keyword-matcher';

// ─── Types ─────────────────────────────────────────────────────────────────

export interface MarketEmbeddingCacheFile {
  model: string;
  dimensions: number;
  created_at: string;
  snapshot_file: string;
  count: number;
  embeddings: Record<string, number[]>;
}

export interface TweetEmbeddingCacheEntry {
  preview: string;
  vector: number[];
}

export interface TweetEmbeddingCacheFile {
  model: string;
  dimensions: number;
  created_at: string;
  updated_at: string;
  embeddings: Record<string, TweetEmbeddingCacheEntry>;
}

export interface EmbeddingMatcherOptions {
  markets: Market[];
  marketEmbeddingsCachePath: string;
  tweetCachePath?: string;
  apiKey?: string;
  minSimilarity?: number;
  maxResults?: number;
  modelName?: string;
}

// ─── Constants ─────────────────────────────────────────────────────────────

const DEFAULT_MODEL = 'gemini-embedding-001';
// Picked from sweep against the labeled eval dataset (150 entries, 79 markets).
// At 0.65 the matcher produces F1=0.312, beating keyword's 0.256.
// Lower values (≤0.60) keep ~0.92 recall but flood FPs; higher values (≥0.70)
// collapse recall as numeric/edge-case tweets fall below the bar.
export const DEFAULT_MIN_SIMILARITY = 0.65;
const DEFAULT_MAX_RESULTS = 5;
const RETRY_DELAYS_MS = [1_000, 2_000, 4_000];

// ─── Helpers ───────────────────────────────────────────────────────────────

function sleep(ms: number): Promise<void> {
  return new Promise((res) => setTimeout(res, ms));
}

function hashText(text: string): string {
  return createHash('sha1').update(text.normalize('NFKC')).digest('hex');
}

function cosineSimilarity(a: number[], b: number[]): number {
  if (a.length !== b.length) {
    throw new Error(`cosineSimilarity: length mismatch (${a.length} vs ${b.length})`);
  }
  let dot = 0;
  let normA = 0;
  let normB = 0;
  for (let i = 0; i < a.length; i++) {
    dot += a[i] * b[i];
    normA += a[i] * a[i];
    normB += b[i] * b[i];
  }
  if (normA === 0 || normB === 0) return 0;
  return dot / (Math.sqrt(normA) * Math.sqrt(normB));
}

// ─── Class ─────────────────────────────────────────────────────────────────

export class EmbeddingMatcher {
  private readonly markets: Market[];
  private readonly marketEmbeddings: Record<string, number[]>;
  private readonly modelName: string;
  private readonly dimensions: number;
  private readonly minSimilarity: number;
  private readonly maxResults: number;
  private readonly tweetCachePath: string | null;
  private readonly tweetCache: Record<string, TweetEmbeddingCacheEntry>;
  private cacheDirty = false;
  private readonly model: ReturnType<GoogleGenerativeAI['getGenerativeModel']>;

  constructor(options: EmbeddingMatcherOptions) {
    this.markets = options.markets;
    this.minSimilarity = options.minSimilarity ?? DEFAULT_MIN_SIMILARITY;
    this.maxResults = options.maxResults ?? DEFAULT_MAX_RESULTS;
    this.modelName = options.modelName ?? DEFAULT_MODEL;
    this.tweetCachePath = options.tweetCachePath ?? null;

    // Load market embeddings.
    if (!existsSync(options.marketEmbeddingsCachePath)) {
      throw new Error(
        `Market embeddings cache not found: ${options.marketEmbeddingsCachePath}. ` +
          `Run scripts/embed-markets.ts first.`,
      );
    }
    const marketCache = JSON.parse(
      readFileSync(options.marketEmbeddingsCachePath, 'utf-8'),
    ) as MarketEmbeddingCacheFile;

    if (marketCache.model !== this.modelName) {
      throw new Error(
        `Market embeddings cache model "${marketCache.model}" doesn't match ` +
          `expected "${this.modelName}". Re-run scripts/embed-markets.ts to regenerate.`,
      );
    }

    this.marketEmbeddings = marketCache.embeddings;
    this.dimensions = marketCache.dimensions;

    // Warn (don't fail) if some input markets aren't in the cache. Eval can
    // still proceed; the missing markets just won't be matched.
    const missing = this.markets.filter((m) => !this.marketEmbeddings[m.id]);
    if (missing.length > 0) {
      console.warn(
        `[embedding-matcher] ${missing.length}/${this.markets.length} input markets ` +
          `not in embeddings cache — they will never be matched. ` +
          `(First missing: ${missing[0].id})`,
      );
    }

    // Init Gemini.
    const apiKey = options.apiKey ?? process.env.GEMINI_API_KEY;
    if (!apiKey) {
      throw new Error(
        'EmbeddingMatcher: GEMINI_API_KEY required. Set via .env.local or constructor.',
      );
    }
    const genAI = new GoogleGenerativeAI(apiKey);
    this.model = genAI.getGenerativeModel({ model: this.modelName });

    // Load tweet cache if a path was supplied.
    this.tweetCache = {};
    if (this.tweetCachePath && existsSync(this.tweetCachePath)) {
      try {
        const raw = JSON.parse(
          readFileSync(this.tweetCachePath, 'utf-8'),
        ) as TweetEmbeddingCacheFile;
        if (raw.model === this.modelName && raw.dimensions === this.dimensions) {
          this.tweetCache = raw.embeddings;
        } else {
          console.warn(
            `[embedding-matcher] Tweet cache model/dim mismatch (cache=${raw.model}/${raw.dimensions}, ` +
              `expected=${this.modelName}/${this.dimensions}). Starting fresh.`,
          );
        }
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        console.warn(`[embedding-matcher] Failed to read tweet cache: ${msg}. Starting fresh.`);
      }
    }
  }

  /**
   * Match a single tweet against the loaded markets, returning the top N
   * markets above the similarity threshold.
   */
  async match(text: string): Promise<MarketMatch[]> {
    const trimmed = text.trim();
    if (!trimmed) return [];

    // Same scam filter the KeywordMatcher uses. Without this, promotional
    // tweets ("🚀 free BTC click here 🚀") still produce a vector and match
    // any topically-related market.
    if (isPromotionalContent(trimmed)) return [];

    const queryVec = await this.embedText(trimmed);

    const scored: Array<{ market: Market; similarity: number }> = [];
    for (const market of this.markets) {
      const vec = this.marketEmbeddings[market.id];
      if (!vec) continue;
      const sim = cosineSimilarity(queryVec, vec);
      if (sim >= this.minSimilarity) {
        scored.push({ market, similarity: sim });
      }
    }

    scored.sort((a, b) => b.similarity - a.similarity);
    return scored.slice(0, this.maxResults).map((s) => ({
      market: s.market,
      confidence: s.similarity,
      matchedKeywords: [],
    }));
  }

  /**
   * Flush any newly-cached tweet embeddings to disk. Call after a batch of
   * matches (e.g., at the end of an eval run).
   */
  flushCache(): void {
    if (!this.cacheDirty || !this.tweetCachePath) return;

    mkdirSync(dirname(this.tweetCachePath), { recursive: true });
    const file: TweetEmbeddingCacheFile = {
      model: this.modelName,
      dimensions: this.dimensions,
      created_at: this.fileCreatedAt(),
      updated_at: new Date().toISOString(),
      embeddings: this.tweetCache,
    };
    writeFileSync(this.tweetCachePath, JSON.stringify(file));
    this.cacheDirty = false;
  }

  /**
   * Stats helper for eval reporting.
   */
  stats(): { cachedTweets: number; modelName: string; dimensions: number } {
    return {
      cachedTweets: Object.keys(this.tweetCache).length,
      modelName: this.modelName,
      dimensions: this.dimensions,
    };
  }

  // ── Internal ────────────────────────────────────────────────────────────

  private async embedText(text: string): Promise<number[]> {
    const key = hashText(text);
    const cached = this.tweetCache[key];
    if (cached) return cached.vector;

    const vec = await this.embedWithRetry(text);
    if (vec.length !== this.dimensions) {
      throw new Error(
        `EmbeddingMatcher: query embedding dimension mismatch ` +
          `(got ${vec.length}, expected ${this.dimensions})`,
      );
    }

    if (this.tweetCachePath) {
      this.tweetCache[key] = {
        preview: text.slice(0, 100),
        vector: vec,
      };
      this.cacheDirty = true;
    }

    return vec;
  }

  private async embedWithRetry(text: string): Promise<number[]> {
    let lastErr: unknown;
    for (let attempt = 0; attempt < RETRY_DELAYS_MS.length + 1; attempt++) {
      try {
        const result = await this.model.embedContent(text);
        const values = result.embedding?.values;
        if (!Array.isArray(values) || values.length === 0) {
          throw new Error('Gemini returned empty embedding');
        }
        return values;
      } catch (err) {
        lastErr = err;
        const msg = err instanceof Error ? err.message : String(err);
        const retriable = /429|rate|quota|503|504|timeout/i.test(msg);
        if (!retriable || attempt >= RETRY_DELAYS_MS.length) break;
        const delay = RETRY_DELAYS_MS[attempt];
        await sleep(delay);
      }
    }
    throw lastErr;
  }

  /**
   * Preserve the original created_at when re-flushing an existing cache file;
   * fall back to "now" if no existing file.
   */
  private fileCreatedAt(): string {
    if (this.tweetCachePath && existsSync(this.tweetCachePath)) {
      try {
        const raw = JSON.parse(
          readFileSync(this.tweetCachePath, 'utf-8'),
        ) as TweetEmbeddingCacheFile;
        if (raw.created_at) return raw.created_at;
      } catch {
        // ignore — fall through
      }
    }
    return new Date().toISOString();
  }
}
